spring.application.name=dataProducer
data.simulator.directory=C:/Users/tapan/Desktop/SELF STUDY/SpringProjects/DriveGuard Project/Data/dataport_publication
data.simulation.year=2021
data.simulation.max.concurrent.trips=5
data.simulation.chance.of.trip=0.40

data.cab.status.topic.name=trip-status
data.cab.location.topic.name=trip-locations


spring.datasource.url=DATABASE_URL_PLACEHOLDER
spring.datasource.username=DATABASE_USERNAME_PLACEHOLDER
spring.datasource.password=DATABASE_PASSWORD_PLACEHOLDER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.kafka.bootstrap-servers=localhost:9092
