spring.application.name=dataProducer
data.simulator.directory=C:/Users/tapan/Desktop/SELF STUDY/SpringProjects/DriveGuard Project/Data/dataport_publication
data.simulation.year=2021

data.cab.status.topic.name=trip-status


spring.datasource.url=jdbc:mysql://localhost:3306/driveguard
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.kafka.bootstrap-servers=localhost:9092
