spring.application.name=rule-engine

data.cab.status.topic.name=trip-status
data.cab.location.topic.name=trip-locations
data.cab.alert.topic.name=anomaly-alerts

# Batch size should match your spring.jpa.properties.hibernate.jdbc.batch_size
data.alerts.batch.size=5

server.port=8082
spring.datasource.url=DATABASE_URL_PLACEHOLDER
spring.datasource.username=DATABASE_USERNAME_PLACEHOLDER
spring.datasource.password=DATABASE_PASSWORD_PLACEHOLDER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#Hibernate Batch size (controls how many entities are kept in memory), also update data.alerts.batch.size
spring.jpa.properties.hibernate.jdbc.batch_size=5

# Optimizes the ordering of inserts to improve batching efficiency
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# The Kafka brokers
spring.kafka.bootstrap-servers=localhost:9092
# A unique ID for your KStreams application
spring.kafka.streams.application-id=driveguard-rule-engine-v1

spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.springframework.kafka.support.serializer.JsonSerde


# Redis Configurations
spring.data.redis.host=localhost
spring.data.redis.port=6379
# TTL for alert keys
app.redis.alert-timeout-minutes=720