spring.application.name=rule-engine

data.cab.status.topic.name=trip-status
data.cab.location.topic.name=trip-locations

server.port=8082
spring.datasource.url=DATABASE_URL_PLACEHOLDER
spring.datasource.username=DATABASE_USERNAME_PLACEHOLDER
spring.datasource.password=DATABASE_PASSWORD_PLACEHOLDER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# The Kafka brokers
spring.kafka.bootstrap-servers=localhost:9092
# A unique ID for your KStreams application
spring.kafka.streams.application-id=driveguard-rule-engine-v1

spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.springframework.kafka.support.serializer.JsonSerde