package com.driveguard.rule_engine.controller;

import com.driveguard.rule_engine.dto.Alert;
import com.driveguard.rule_engine.service.AlertPersistenceService;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springdoc.core.annotations.ParameterObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/alerts")
@CrossOrigin(origins = "*", allowedHeaders = "*", methods = {RequestMethod.GET, RequestMethod.POST, RequestMethod.PUT})
@Tag(name = "Alert Management", description = "Endpoints for managing and retrieving alerts generated by the rule engine")
public class AlertController {

    private final AlertPersistenceService alertPersistenceService;

    @Autowired
    public AlertController(AlertPersistenceService alertPersistenceService) {
        this.alertPersistenceService = alertPersistenceService;
    }

    @GetMapping("/{tripNumber}" )
    public ResponseEntity<Page<Alert>> getAlertsByTripNumber(@PathVariable String tripNumber,
                                                             @ParameterObject Pageable pageable) {
        return ResponseEntity.ok(alertPersistenceService.getAlertsByTripNumber(tripNumber, pageable));
    }

}
